apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hytale

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - persistentvolumeclaim.yaml

labels:
  - pairs:
      app.kubernetes.io/name: hytale-server
      app.kubernetes.io/managed-by: kustomize
