apiVersion: v1
kind: Service
metadata:
  name: hytale-server
  namespace: hytale
spec:
  type: LoadBalancer
  selector:
    app: hytale-server
  ports:
    - name: quic
      protocol: UDP
      port: 5520
      targetPort: 5520
