{{- if or .Values.hytale.sessionToken .Values.hytale.identityToken .Values.curseforge.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hytale-server.fullname" . }}-secrets
  labels:
    {{- include "hytale-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.hytale.sessionToken }}
  session-token: {{ .Values.hytale.sessionToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.hytale.identityToken }}
  identity-token: {{ .Values.hytale.identityToken | b64enc | quote }}
  {{- end }}
  {{- if and .Values.curseforge.enabled .Values.curseforge.apiKey (not .Values.curseforge.apiKeySecret.name) }}
  curseforge-api-key: {{ .Values.curseforge.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
